# Generated by Django 5.0 on 2024-02-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_quiz_answer_quiz_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_answer',
            name='correct_quiz_answer',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='correct_quiz_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
