# Generated by Django 5.0 on 2024-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_remove_quiz_answer_correct_quiz_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
