# Generated by Django 5.0 on 2024-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_alter_quiz_model_image_alter_quiz_model_quiz_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quizes/media/uploads'),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_banner',
            field=models.ImageField(blank=True, null=True, upload_to='quizes/media/uploads'),
        ),
    ]
